# =============================================================================
# COMMON PARAMETERS FOR USER API
# =============================================================================
#
# This file contains reusable parameter definitions for the User API.
# Parameters are organized by category for easy reference and maintenance.
#
# =============================================================================

# -----------------------------------------------------------------------------
# PATH PARAMETERS
# -----------------------------------------------------------------------------

organizationId:
  name: organizationId
  in: path
  description: Organization ID
  required: true
  schema:
    type: string
    pattern: '^org_[a-zA-Z0-9_]+$'
    example: org_acme_corp_12345

userId:
  name: userId
  in: path
  description: User ID
  required: true
  schema:
    type: string
    format: uuid
    example: "123e4567-e89b-12d3-a456-426614174000"

# -----------------------------------------------------------------------------
# PAGINATION PARAMETERS
# -----------------------------------------------------------------------------

page:
  name: page
  in: query
  description: Page number for pagination
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1
    example: 1

limit:
  name: limit
  in: query
  description: Number of items per page
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
    example: 20

# -----------------------------------------------------------------------------
# SORTING PARAMETERS
# -----------------------------------------------------------------------------

sortBy:
  name: sortBy
  in: query
  description: Field to sort by
  required: false
  schema:
    type: string
    enum: [name, email, role, lastLogin, createdAt, updatedAt]
    default: name
  example: name

sortOrder:
  name: sortOrder
  in: query
  description: Sort order
  required: false
  schema:
    type: string
    enum: [asc, desc]
    default: asc
  example: asc

# -----------------------------------------------------------------------------
# SEARCH AND FILTERING PARAMETERS
# -----------------------------------------------------------------------------

search:
  name: search
  in: query
  description: Search in user names, emails, and job titles
  required: false
  schema:
    type: string
    minLength: 1
    maxLength: 100
  example: "john doe"

role:
  name: role
  in: query
  description: Filter by user role
  required: false
  schema:
    type: string
    enum: [admin, manager, employee, user, member]
  example: admin

status:
  name: status
  in: query
  description: Filter by user status
  required: false
  schema:
    type: string
    enum: [active, inactive, pending, suspended, archived]
  example: active

department:
  name: department
  in: query
  description: Filter by department
  required: false
  schema:
    type: string
  example: "Engineering"

# -----------------------------------------------------------------------------
# DATE FILTERING PARAMETERS
# -----------------------------------------------------------------------------

lastLoginAfter:
  name: lastLoginAfter
  in: query
  description: Filter users who logged in after this date
  required: false
  schema:
    type: string
    format: date-time
  example: "2024-01-01T00:00:00Z"

createdAfter:
  name: createdAfter
  in: query
  description: Filter users created after this date
  required: false
  schema:
    type: string
    format: date-time
  example: "2024-01-01T00:00:00Z"

createdBefore:
  name: createdBefore
  in: query
  description: Filter users created before this date
  required: false
  schema:
    type: string
    format: date-time
  example: "2024-12-31T23:59:59Z"

# -----------------------------------------------------------------------------
# INCLUSION PARAMETERS
# -----------------------------------------------------------------------------

includeProfile:
  name: includeProfile
  in: query
  description: Include user profile information
  required: false
  schema:
    type: boolean
    default: false
  example: true

includePermissions:
  name: includePermissions
  in: query
  description: Include user permissions
  required: false
  schema:
    type: boolean
    default: false
  example: true

includeActivity:
  name: includeActivity
  in: query
  description: Include recent activity information
  required: false
  schema:
    type: boolean
    default: false
  example: true

includePreferences:
  name: includePreferences
  in: query
  description: Include user preferences
  required: false
  schema:
    type: boolean
    default: false
  example: true

# -----------------------------------------------------------------------------
# BULK OPERATION PARAMETERS
# -----------------------------------------------------------------------------

hardDelete:
  name: hardDelete
  in: query
  description: Permanently delete user (admin only)
  required: false
  schema:
    type: boolean
    default: false
  example: false

force:
  name: force
  in: query
  description: Force operation even with validation warnings
  required: false
  schema:
    type: boolean
    default: false
  example: false

# -----------------------------------------------------------------------------
# EXPORT PARAMETERS
# -----------------------------------------------------------------------------

format:
  name: format
  in: query
  description: Export format
  required: false
  schema:
    type: string
    enum: [json, csv, xlsx]
    default: json
  example: csv

includeFields:
  name: includeFields
  in: query
  description: Comma-separated list of fields to include in export
  required: false
  schema:
    type: string
  example: "name,email,role,department"

# =============================================================================
# END OF COMMON PARAMETERS
# =============================================================================